// @generated by protoc-gen-connect-web v0.1.0 with parameter "target=ts"
// @generated from file auth/v1/auth.proto (package auth.v1, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import {CommonResponse, LoginRequest, TokenRequest, TokenResponse} from "./auth_pb.js";
import {MethodKind} from "@bufbuild/protobuf";

/**
 * @generated from service auth.v1.AuthService
 */
export const AuthService = {
  typeName: "auth.v1.AuthService",
  methods: {
    /**
     * @generated from rpc auth.v1.AuthService.Login
     */
    login: {
      name: "Login",
      I: LoginRequest,
      O: TokenResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc auth.v1.AuthService.RevokeToken
     */
    revokeToken: {
      name: "RevokeToken",
      I: TokenRequest,
      O: CommonResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc auth.v1.AuthService.RefreshToken
     */
    refreshToken: {
      name: "RefreshToken",
      I: TokenRequest,
      O: TokenResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

