// @generated by protoc-gen-connect-web v0.1.0 with parameter "target=ts"
// @generated from file user/v1/user.proto (package user.v1, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import {CommonUUIDRequest, CreateUserRequest, FindAllUsersRequest, FindAllUsersResponse, UpdateUserRequest, User} from "./user_pb.js";
import {MethodKind} from "@bufbuild/protobuf";

/**
 * @generated from service user.v1.UserService
 */
export const UserService = {
  typeName: "user.v1.UserService",
  methods: {
    /**
     * @generated from rpc user.v1.UserService.FindAllUsers
     */
    findAllUsers: {
      name: "FindAllUsers",
      I: FindAllUsersRequest,
      O: FindAllUsersResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Find User by ID
     *
     * @generated from rpc user.v1.UserService.FindUserByID
     */
    findUserByID: {
      name: "FindUserByID",
      I: CommonUUIDRequest,
      O: User,
      kind: MethodKind.Unary,
    },
    /**
     * Create new User
     *
     * @generated from rpc user.v1.UserService.CreateUser
     */
    createUser: {
      name: "CreateUser",
      I: CreateUserRequest,
      O: CommonUUIDRequest,
      kind: MethodKind.Unary,
    },
    /**
     * Update User by ID
     *
     * @generated from rpc user.v1.UserService.UpdateUser
     */
    updateUser: {
      name: "UpdateUser",
      I: UpdateUserRequest,
      O: CommonUUIDRequest,
      kind: MethodKind.Unary,
    },
    /**
     * Delete User
     *
     * @generated from rpc user.v1.UserService.DeleteUser
     */
    deleteUser: {
      name: "DeleteUser",
      I: CommonUUIDRequest,
      O: CommonUUIDRequest,
      kind: MethodKind.Unary,
    },
  }
} as const;

