// @generated by protoc-gen-connect-web v0.1.0 with parameter "target=ts"
// @generated from file permission/v1/permission.proto (package permission.v1, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import {CommonResponse, CommonUUIDRequest, CreatePermissionRequest, FindAllPermissionsRequest, FindAllPermissionsResponse, Permission, UpdatePermissionRequest} from "./permission_pb.js";
import {MethodKind} from "@bufbuild/protobuf";

/**
 * @generated from service permission.v1.PermissionService
 */
export const PermissionService = {
  typeName: "permission.v1.PermissionService",
  methods: {
    /**
     * Find all Permissions
     *
     * @generated from rpc permission.v1.PermissionService.FindAllPermissions
     */
    findAllPermissions: {
      name: "FindAllPermissions",
      I: FindAllPermissionsRequest,
      O: FindAllPermissionsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Find Permission by ID
     *
     * @generated from rpc permission.v1.PermissionService.FindPermissionByID
     */
    findPermissionByID: {
      name: "FindPermissionByID",
      I: CommonUUIDRequest,
      O: Permission,
      kind: MethodKind.Unary,
    },
    /**
     * Create new Permission
     *
     * @generated from rpc permission.v1.PermissionService.CreatePermission
     */
    createPermission: {
      name: "CreatePermission",
      I: CreatePermissionRequest,
      O: CommonResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Update Permission by ID
     *
     * @generated from rpc permission.v1.PermissionService.UpdatePermission
     */
    updatePermission: {
      name: "UpdatePermission",
      I: UpdatePermissionRequest,
      O: CommonResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Delete Permission
     *
     * @generated from rpc permission.v1.PermissionService.DeletePermission
     */
    deletePermission: {
      name: "DeletePermission",
      I: CommonUUIDRequest,
      O: CommonResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

