// @generated by protoc-gen-es v0.0.10 with parameter "target=ts"
// @generated from file role/v1/role.proto (package role.v1, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import type {BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage} from "@bufbuild/protobuf";
import {Message, proto3, protoInt64} from "@bufbuild/protobuf";

/**
 * @generated from message role.v1.CommonUUIDRequest
 */
export class CommonUUIDRequest extends Message<CommonUUIDRequest> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  constructor(data?: PartialMessage<CommonUUIDRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime = proto3;
  static readonly typeName = "role.v1.CommonUUIDRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CommonUUIDRequest {
    return new CommonUUIDRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CommonUUIDRequest {
    return new CommonUUIDRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CommonUUIDRequest {
    return new CommonUUIDRequest().fromJsonString(jsonString, options);
  }

  static equals(a: CommonUUIDRequest | PlainMessage<CommonUUIDRequest> | undefined, b: CommonUUIDRequest | PlainMessage<CommonUUIDRequest> | undefined): boolean {
    return proto3.util.equals(CommonUUIDRequest, a, b);
  }
}

/**
 * @generated from message role.v1.CommonResponse
 */
export class CommonResponse extends Message<CommonResponse> {
  /**
   * @generated from field: string data = 1;
   */
  data = "";

  constructor(data?: PartialMessage<CommonResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime = proto3;
  static readonly typeName = "role.v1.CommonResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "data", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CommonResponse {
    return new CommonResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CommonResponse {
    return new CommonResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CommonResponse {
    return new CommonResponse().fromJsonString(jsonString, options);
  }

  static equals(a: CommonResponse | PlainMessage<CommonResponse> | undefined, b: CommonResponse | PlainMessage<CommonResponse> | undefined): boolean {
    return proto3.util.equals(CommonResponse, a, b);
  }
}

/**
 * @generated from message role.v1.FindAllRolesRequest
 */
export class FindAllRolesRequest extends Message<FindAllRolesRequest> {
  /**
   * @generated from field: int64 page = 1;
   */
  page = protoInt64.zero;

  constructor(data?: PartialMessage<FindAllRolesRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime = proto3;
  static readonly typeName = "role.v1.FindAllRolesRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "page", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): FindAllRolesRequest {
    return new FindAllRolesRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): FindAllRolesRequest {
    return new FindAllRolesRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): FindAllRolesRequest {
    return new FindAllRolesRequest().fromJsonString(jsonString, options);
  }

  static equals(a: FindAllRolesRequest | PlainMessage<FindAllRolesRequest> | undefined, b: FindAllRolesRequest | PlainMessage<FindAllRolesRequest> | undefined): boolean {
    return proto3.util.equals(FindAllRolesRequest, a, b);
  }
}

/**
 * @generated from message role.v1.FindAllRolesResponse
 */
export class FindAllRolesResponse extends Message<FindAllRolesResponse> {
  /**
   * @generated from field: int64 totalPage = 1;
   */
  totalPage = protoInt64.zero;

  /**
   * @generated from field: int64 currentPage = 2;
   */
  currentPage = protoInt64.zero;

  /**
   * Roles
   *
   * @generated from field: repeated role.v1.Role data = 3;
   */
  data: Role[] = [];

  constructor(data?: PartialMessage<FindAllRolesResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime = proto3;
  static readonly typeName = "role.v1.FindAllRolesResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "totalPage", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "currentPage", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "data", kind: "message", T: Role, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): FindAllRolesResponse {
    return new FindAllRolesResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): FindAllRolesResponse {
    return new FindAllRolesResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): FindAllRolesResponse {
    return new FindAllRolesResponse().fromJsonString(jsonString, options);
  }

  static equals(a: FindAllRolesResponse | PlainMessage<FindAllRolesResponse> | undefined, b: FindAllRolesResponse | PlainMessage<FindAllRolesResponse> | undefined): boolean {
    return proto3.util.equals(FindAllRolesResponse, a, b);
  }
}

/**
 * @generated from message role.v1.Role
 */
export class Role extends Message<Role> {
  /**
   * Output only. Id of the role.
   *
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * Output only. Name of the role.
   *
   * @generated from field: string name = 2;
   */
  name = "";

  /**
   * Output only. Email of the role.
   *
   * @generated from field: string slug = 3;
   */
  slug = "";

  /**
   * Output only. isFullAccess of the role.
   *
   * @generated from field: bool isFullAccess = 4;
   */
  isFullAccess = false;

  /**
   * Output only. Status of the role.
   *
   * @generated from field: int32 status = 5;
   */
  status = 0;

  constructor(data?: PartialMessage<Role>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime = proto3;
  static readonly typeName = "role.v1.Role";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "slug", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "isFullAccess", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 5, name: "status", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Role {
    return new Role().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Role {
    return new Role().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Role {
    return new Role().fromJsonString(jsonString, options);
  }

  static equals(a: Role | PlainMessage<Role> | undefined, b: Role | PlainMessage<Role> | undefined): boolean {
    return proto3.util.equals(Role, a, b);
  }
}

/**
 * The request create new Role
 *
 * @generated from message role.v1.CreateRoleRequest
 */
export class CreateRoleRequest extends Message<CreateRoleRequest> {
  /**
   * @generated from field: string name = 1;
   */
  name = "";

  /**
   * @generated from field: string slug = 2;
   */
  slug = "";

  /**
   * @generated from field: int32 status = 3;
   */
  status = 0;

  /**
   * @generated from field: optional bool isFullAccess = 4;
   */
  isFullAccess?: boolean;

  /**
   * List Permissions ID
   *
   * @generated from field: repeated string permissions = 5;
   */
  permissions: string[] = [];

  constructor(data?: PartialMessage<CreateRoleRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime = proto3;
  static readonly typeName = "role.v1.CreateRoleRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "slug", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "status", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 4, name: "isFullAccess", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 5, name: "permissions", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateRoleRequest {
    return new CreateRoleRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateRoleRequest {
    return new CreateRoleRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateRoleRequest {
    return new CreateRoleRequest().fromJsonString(jsonString, options);
  }

  static equals(a: CreateRoleRequest | PlainMessage<CreateRoleRequest> | undefined, b: CreateRoleRequest | PlainMessage<CreateRoleRequest> | undefined): boolean {
    return proto3.util.equals(CreateRoleRequest, a, b);
  }
}

/**
 * The request update Role
 *
 * @generated from message role.v1.UpdateRoleRequest
 */
export class UpdateRoleRequest extends Message<UpdateRoleRequest> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: optional string name = 2;
   */
  name?: string;

  /**
   * @generated from field: optional string slug = 3;
   */
  slug?: string;

  /**
   * @generated from field: optional bool isFullAccess = 4;
   */
  isFullAccess?: boolean;

  /**
   * @generated from field: optional int32 status = 5;
   */
  status?: number;

  /**
   * List Permissions ID
   *
   * @generated from field: repeated string permissions = 6;
   */
  permissions: string[] = [];

  constructor(data?: PartialMessage<UpdateRoleRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime = proto3;
  static readonly typeName = "role.v1.UpdateRoleRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 3, name: "slug", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 4, name: "isFullAccess", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 5, name: "status", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true },
    { no: 6, name: "permissions", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateRoleRequest {
    return new UpdateRoleRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateRoleRequest {
    return new UpdateRoleRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateRoleRequest {
    return new UpdateRoleRequest().fromJsonString(jsonString, options);
  }

  static equals(a: UpdateRoleRequest | PlainMessage<UpdateRoleRequest> | undefined, b: UpdateRoleRequest | PlainMessage<UpdateRoleRequest> | undefined): boolean {
    return proto3.util.equals(UpdateRoleRequest, a, b);
  }
}

