// @generated by protoc-gen-connect-web v0.1.0 with parameter "target=ts"
// @generated from file role/v1/role.proto (package role.v1, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import {CommonNameRequest, CommonResponse, CreateRoleRequest, FindAllRolesRequest, FindAllRolesResponse, Role, UpdateRoleRequest} from "./role_pb.js";
import {MethodKind} from "@bufbuild/protobuf";

/**
 * @generated from service role.v1.RoleService
 */
export const RoleService = {
  typeName: "role.v1.RoleService",
  methods: {
    /**
     * @generated from rpc role.v1.RoleService.FindAllRoles
     */
    findAllRoles: {
      name: "FindAllRoles",
      I: FindAllRolesRequest,
      O: FindAllRolesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Find Role by Name
     *
     * @generated from rpc role.v1.RoleService.FindRoleByName
     */
    findRoleByName: {
      name: "FindRoleByName",
      I: CommonNameRequest,
      O: Role,
      kind: MethodKind.Unary,
    },
    /**
     * Create new Role
     *
     * @generated from rpc role.v1.RoleService.CreateRole
     */
    createRole: {
      name: "CreateRole",
      I: CreateRoleRequest,
      O: CommonResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Update Role by ID
     *
     * @generated from rpc role.v1.RoleService.UpdateRole
     */
    updateRole: {
      name: "UpdateRole",
      I: UpdateRoleRequest,
      O: CommonResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Delete Role
     *
     * @generated from rpc role.v1.RoleService.DeleteRole
     */
    deleteRole: {
      name: "DeleteRole",
      I: CommonNameRequest,
      O: CommonResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

